### ISSUE TITLE
MemorySize invalid

### ISSUE THREAD

**Issue by revmischa** [daaru00/serverless-plugin-greengrass#1]
Greengrass: Deploy error: Deployment xxxxxxxxxxx of type NewDeployment for group xxxxxxxxxxx failed error: Greengrass deployment error: unable to execute download step in deployment. 
error while processing: unable to load the group file downloaded: lambda definition is invalid, functionArn: arn:aws:lambda:eu-west-1:xxxxxxxxxxx:function:dev-monitor:4: [1024] is invalid [MemorySize]

Is there some way to unset memorySize?

**Comment by daaru00** [comment]
Hi @revmischa,

should not be required to remove that configuration, it seems instead an error parsing the memory value.
Can you share your `serverless.yml`?

**Comment by revmischa** [comment]
```
service: vohon

plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters
  - serverless-wsgi
  - serverless-plugin-greengrass

custom:
  stackName: ${self:service}-${self:provider.stage}

  # our app configuration
  monitor:
    schedule: 1 minute
  # plugins:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: false
    slim: true
    useDownloadCache: true
    useStaticCache: true
    noDeploy:
      - boto3
      - botocore
      - docutils
  greengrass:
    autoDeploy: true # set to "false" to disable automatic deploy after "sls deploy"
    groupId: dcfdeb64-7114-4133-a64c-1111  =
    include:
      # only deploy these functions to greengrass <-- this doesn't work; it tries to deploy app too
      - monitor
    exclude:
      - app

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-1'}

package:
  exclude:
    - node_modules/**
    - venv/**
    - vohon/instance.cfg
    - instance.cfg
    - doc/**
    - '**/__pycache__/**'
    - '**/__pycache__'
    - ".#*"
    - ".bento/**"

functions:
  app:  # main flask entry point
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    memorySize: 512
    timeout: 10

  monitor:  # client monitor poller
    handler: vohon/client/handler.monitor
    events:
      - schedule: "rate(${self:custom.monitor.schedule})"
    timeout: 30
```

if I set greengrass->defaults->memorySize then it does try to deploy

**Comment by daaru00** [comment]
not sure if I fully understood, if you set defaults->memorySize deploy ends successfully?

Can you do a try removing `memorySize: 512` from your "app" function and re-deploy?

Just to be sure, are you using the latest version of the plugin? (`npm list --depth=0` to list packages versions).

**Comment by revmischa** [comment]
Yeah. app doesn't matter if it's excluded. 
```
├── husky@4.2.1
├── serverless@1.61.3
├── serverless-pseudo-parameters@2.5.0
├── serverless-python-requirements@5.0.1
└── serverless-wsgi@1.7.4
```

**Comment by revmischa** [comment]
It's a super cool project though. Thanks for putting this together. I hope I can contribute something.
Being able to change the IsolationMode would be very helpful I think

**Comment by revmischa** [comment]
BTW I tried running this on a linux laptop and got this error:
```
  The CloudFormation template is invalid: [/Resources/GreengrassFunctionDefinition/Type/InitialVersion/Functions/0/FunctionArn/Fn::Join/1/1/Fn::GetAtt/0] 'null' values are not allowed in templates
```
The definition looks like:
```
          "Functions": [
            {
              "Id": "myapp-dev-monitor",
              "FunctionArn": {
                "Fn::Join": [
                  ":",
                  [
                    {
                      "Fn::GetAtt": [
                        "MonitorLambdaFunction",
                        "Arn"
                      ]
                    },
                    {
                      "Fn::GetAtt": [
                        null,
                        "Version"
                      ]
                    }
                  ]
                ]
              },
```

**Comment by daaru00** [comment]
There isn't this plugin shown from the list of modules you posted, is it installed correctly? can you please do a double-check?

> Can you do a try removing memorySize: 512 from your "app" function and re-deploy?

Have you done this test?

> BTW I tried running this on a linux laptop and got this error:

Serverless plugins are mainly cross-os, testing on different OS does not have any effects. Please open a different issue to track the last error separately.

**Comment by revmischa** [comment]
```
├── husky@4.2.1
├── serverless@1.61.3
├── serverless-plugin-greengrass@1.3.3
├── serverless-pseudo-parameters@2.5.0
├── serverless-python-requirements@5.0.1
└── serverless-wsgi@1.7.4
```

If I comment `memorySize` from both GG `defaults` and `app` then it appears to deploy successfully

**Comment by daaru00** [comment]
ook, it seems an issue on memorySize value parsing/transformation. Thank you for details, let me dig into it in these days to spot the bug 👍

**Comment by daaru00** [comment]
Hi @revmischa,

I found the issue, seems not directly related to `memorySize: 512` but with the [default value](https://github.com/daaru00/serverless-plugin-greengrass/blob/6ba669ce4cdf3253849e6dd15671dd195e3809cb/helpers/resources/functionDefinition.js#L38) of 1024. 

The [FunctionConfiguration](https://docs.aws.amazon.com/greengrass/latest/apireference/definitions-functionconfiguration.html) declaration is expressed in KB, not in MB as "normal" Lambdas. So 1024 seems too low (official documentation does not say anything about a minimum value).

this fail:
```yaml
app:
    handler: index.handler
    greengrass:
        memorySize: 1024
```
this works:
```yaml
app:
    handler: index.handler
    greengrass:
        memorySize: 2048  # 2MB expressed in KB (seems the minimum allowed value)
```
this works:
```yaml
app:
    handler: index.handler
    greengrass:
        memorySize: 131072  # 128 MB expressed in KB (the new default value)
```

I fixed the default value, added an additional check during deploy (with a default fallback in case of wrong value) and improved documentation about memory size value. 
You can upgrade this plugin to `1.3.4` and this error should be fixed, can you confirm?
