### ISSUE TITLE
Can't read configuration in other file.

### ISSUE THREAD

**Issue by takanorig** [daaru00/serverless-plugin-greengrass#8]
Hi,
I'm using this plugin for the first time.

When I defile `custom` configuration in one file, this plugin can read them.

- serverless.yml
```yaml
custom:
    greengrass:
        groupId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        autoDeploy: false

functions:
    my_func:
        handler:my_func.function_handler
        greengrass:
            pinned: true
```

But, when I define `custom` configuration in other file, this plugin can't read them.

- serverless.yml
```yaml
custom: ${file(../customs/${opt:stage, 'dev'}.yml)}

functions:
    my_func:
        handler:my_func.function_handler
        greengrass:
            pinned: true
```

- customs/dev.yml
```yaml
greengrass:
    groupId: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    autoDeploy: false
```

it showed the following debug message.

```
No Group ID defined, skipping..
```

Can it be defined the configuration in other file?
